default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :release do
    match(
      type: "appstore",
      readonly: true
    )

    build_ios_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "org.stormycloud.i2pbridge" => "i2pbridge-appstore-profile"
        }
      }
    )

    upload_to_testflight(
      api_key: app_store_connect_api_key
    )
  end
end
