name: Flutter CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4
      - run: flutter pub get
      - run: flutter build ios --no-codesign