name: Flutter CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
      
      - name: Debug runner environment
        run: |
          echo "Current user: $(whoami)"
          echo "User ID: $(id)"
          echo "Home directory: $HOME"
          echo "Current directory: $(pwd)"
          ls -la /Users/ || echo "Cannot list /Users/"
          echo "Runner temp: $RUNNER_TEMP"
          echo "Runner workspace: $GITHUB_WORKSPACE"
      
      - name: Clean build artifacts and cache
        run: |
          flutter clean || true
          rm -rf .dart_tool
          rm -rf build
          rm -rf ~/.pub-cache/hosted
          rm -rf ios/Pods
          rm -f ios/Podfile.lock
          
      - name: Get Flutter dependencies
        run: |
          flutter pub cache repair
          flutter pub get
          
      - name: Install iOS dependencies
        run: |
          cd ios
          pod install
          cd ..
          
      - run: flutter build ios --no-codesign
      - run: flutter pub get
      - run: flutter build ios --no-codesign --dart-define=I2P_BRIDGE_API_KEY=${{ secrets.I2P_BRIDGE_API_KEY }}
  build-android:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0

      - name: Clean build artifacts and cache
        run: |
          flutter clean || true
          rm -rf .dart_tool
          rm -rf build
          rm -rf ~/.pub-cache/hosted
          rm -rf android/.gradle
          
      - name: Get Flutter dependencies
        run: |
          flutter pub cache repair
          flutter pub get
          
      - run: flutter build apk --debug

