name: Flutter CI

on:
  pull_request:
    branches: [ main ]

jobs:

  build-ios:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4
      - run: flutter pub get
      - run: flutter build ios --no-codesign

  build-android:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4

      - name: Cache Flutter packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-pub

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - run: flutter pub get
      - run: flutter build apk --debug
