name: iOS Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: [self-hosted, macOS]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Debug - Check file structure
      run: |
        echo "Current directory:"
        pwd
        echo "Contents:"
        ls -la
        echo "iOS directory contents:"
        ls -la ios/
        
    - name: Set up SSH for Match
      env:
        MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$MATCH_GIT_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        
    - name: Install dependencies
      working-directory: ./ios
      run: |
        echo "In iOS directory:"
        pwd
        ls -la
        bundle install
        pod install
        
    - name: Build and upload to TestFlight
      working-directory: ./ios
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        MATCH_GIT_URL: "git@github.com:WaxySteelWorm/ios-certificates.git"
      run: |
        bundle exec fastlane release
