name: Release iOS App

on:
  push:
    tags:
      - 'v*'

jobs:
  release_ios:
    runs-on: [self-hosted, macOS]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run build
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
      run: |
        export PATH="/opt/homebrew/bin:$PATH"
        cd ios
        rm -rf Pods
        rm -f Podfile.lock
        pod install
        cd ..
        flutter clean
        flutter pub get
        mkdir -p ~/.ssh
        echo "$MATCH_GIT_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        cd ios
        bundle exec fastlane release

        
