name: Release iOS App

on:
  push:
    tags:
      - 'v*'

jobs:
  release_ios:
    runs-on: [self-hosted]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure Git for Match
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.MATCH_GIT_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Run Fastlane Build
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      run: |
        cd ios
        bundle exec fastlane release
