name: iOS Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install CocoaPods
      run: |
        gem install cocoapods
        
    - name: Install pods
      working-directory: ./ios
      run: pod install
      
    - name: Unlock keychain
      run: |
        security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" ~/Library/Keychains/login.keychain-db
        security set-keychain-settings -lut 21600 ~/Library/Keychains/login.keychain-db
        
    - name: Build and upload to TestFlight
      working-directory: ./ios
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPSTORE_CONNECT_API_KEY }}
      run: |
        bundle install
        bundle exec fastlane release
